name: snap_stream
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.1
  collection: ^1.16.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.3.4
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^6.1.0
  hooks_riverpod: ^2.3.4
  image: ^4.0.15
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  lottie: ^2.3.2
  riverpod_annotation: ^2.0.4
  share_plus: ^6.3.2
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  video_player: ^2.4.7
  video_thumbnail: ^0.5.2

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json
